version: '3'

services:
  nats-server:
    image: nats
    restart: always
    ports:
      - 4222:4222
  
  redis-server:
    image: redis
    command: redis-server --requirepass SUASENHA --appendonly yes
    hostname: redis
    ports:
      - "6379:6379"

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_register
    ports:
      - "3306:3306"